global:
  name: Hive Ventures Landscape
  short_name: Hive
  repo: Hive-Ventures/hive-landscape
  website: https://www.hiveventures.io/landscape
  short_domain: www.hiveventures.io/landscape
  company_url: https://www.hiveventures.io
  email: ideas@hiveventures.io
  self: https://www.crunchbase.com/organization/hive-ventures-0ae4
  #slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: Hive Ventures Landscape
    fb_admin: wanghauw
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@hiveventuresio'
    #google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    #ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: GraphQL Foundation Member
  flags:
    hide_license_for_categories:
      - GraphQL Adopter
      - GraphQL Foundation Member
twitter:
  search: www.hiveventures.io/landscape
  url: https://www.hiveventures.io/landscape
  text: Hive Ventures Landscape
relation:
  label: GraphQL Relation
  url: graphql
  values:
    - id: hosted
      label: GraphQL Foundation Projects
      children:
        - id: foundationproject
          label: GraphQL Foundation Projects
          prefix: GraphQL
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: GraphQL Foundation Project
          big_picture_color: rgb(24,54,114)
    - id: company
      label: GraphQL Foundation Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: GraphQL Foundation Member Products/Projects
      tag: GraphQL Foundation Member
    - id: false
      label: Non-GraphQL Foundation Member Products/Projects
      url: 'no'
membership:
  General:
    name: GraphQL
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>Hive Ventures Landscape</h1> The Hive Ventures Landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a target="_blank" href="http://landscape.cncf.io">CNCF landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://www.hiveventures.io
    image: /images/info1.jpg
    title: Hive Ventures
presets:
#  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
#    label: Open source cards by age
#  - url: /license=apache-license-2-0
#    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: GraphQL Landscape
    fullscreen_header: See the interactive landscape at l.graphql.org
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 4
        width: 475
        height: 160
        top: 0
        left: 0
        color: rgb(4,81,49)
        fit_width: true
      - type: HorizontalCategory
        category: Services
        rows: 3
        width: 180
        height: 160
        top: 0
        left: 495
        color: rgb(7,136,62)
        fit_width: true
      - type: HorizontalCategory
        category: Databases
        rows: 3
        width: 275
        height: 160
        top: 0
        left: 695
        color: rgb(79,121,13)
        fit_width: true
      - type: HorizontalCategory
        category: GraphQL Adopter
        rows: 6
        width: 970
        height: 195
        top: 180
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: GraphQL Foundation Member
        rows: 4
        width: 650
        height: 150
        top: 390
        left: 0
        color: rgb(103,66,18)
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 390
        left: 665
        children:
          - type: text
            text: |
                This landscape is intended as a map to explore the Taiwan big data and AI landscape, and also shows the portfolio companies of Hive Ventures.
            top: 45
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: www.hiveventures.io/landscape
            top: 95
            left: 10
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 90
            right: 105
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 90
            right: 10
            top: 10
            title: Hive Ventures Logo
#test:
#  header: Hive Ventures Landscape
#  section: Hive Portfolio
#  logo: twitter.svg
